apps/config/routes.rb
Rails.application.routes.draw do
  resources :calenders
  resources :rooms

  root "rooms#index"

  devise_for :admins, controllers: {
                        registrations: "admins/registrations",
                        sessions: "admins/sessions",
                      }

  devise_for :users, controllers: {
                       registrations: "users/registrations",
                       sessions: "users/sessions",
                     }
end

apps/app/views/layouts/_navi.html.erb
<nav class="bg-purple-900 text-white flex justify-between">
  <ul class="px-10 py-4 flex space-x-3">
    <%= content_tag(:li, class: "cursor-pointer") do link_to("HOME", root_path) end if !admin_signed_in? %>
    <%= content_tag(:li, class: "cursor-pointer") do link_to("ROOM", root_path) end if admin_signed_in? %>
    <%= content_tag(:li, class: "cursor-pointer") do link_to("Calender", calenders_path) end if admin_signed_in? %>
    <%= content_tag(:li, class: "cursor-pointer") do link_to("Register", new_user_registration_path) end if !user_signed_in? && !admin_signed_in? %>
    <%= content_tag(:li, class: "cursor-pointer") do link_to("Login", new_user_session_path) end if !user_signed_in? && !admin_signed_in? %>
    <%= content_tag(:li, class: "cursor-pointer") do link_to("Admin Register", new_admin_registration_path) end if !user_signed_in? && !admin_signed_in? %>
    <%= content_tag(:li, class: "cursor-pointer") do link_to("Admin Login", new_admin_session_path) end if !user_signed_in? && !admin_signed_in? %>
    <%= content_tag(:li, class: "cursor-pointer") do link_to("Logout", destroy_user_session_path, data: {turbo_method: :delete}) end if user_signed_in? %>
    <%= content_tag(:li, class: "cursor-pointer") do link_to("Admin Logout", destroy_user_session_path, data: {turbo_method: :delete}) end if admin_signed_in? %>
  </ul>
</nav>

apps/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apps</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navi' %>
    <main class="container mx-auto mt-28 px-5 flex">
      <% if notice.present? %>
        <p class="alarm text-green-500" id="notice"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="alarm text-pink-500" id="alert"><%= alert%></p>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>