apps/config/routes.rb
Rails.application.routes.draw do
  resources :calenders
  resources :rooms

  root "rooms#index"

  devise_for :admins, controllers: {
                        registrations: "admins/registrations",
                        sessions: "admins/sessions",
                      }

  devise_for :users, controllers: {
                       registrations: "users/registrations",
                       sessions: "users/sessions",
                     }
end

apps/app/models/room.rb
class Room < ApplicationRecord
end

apps/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name, :profile)
    end
end

apps/app/helpers/rooms_helper.rb
module RoomsHelper
end

apps/app/views/rooms/_form.html.erb
<%= form_with(model: room, class: "contents") do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :profile %>
    <%= form.text_area :profile, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

apps/app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Room Name:</strong>
    <%= room.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Profile:</strong>
    <%= room.profile %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show", room, class: "lnk_btn" %>
    <%= link_to "Edit", edit_room_path(room), class: "lnk_btn ml-2" if admin_signed_in? %>
    <hr class="mt-6">
  <% end %>
</div>

apps/app/views/rooms/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing room</h1>

  <%= render "form", room: @room %>

  <%= link_to "Show this room", @room, class: "ml-2 lnk_btn" %>
  <%= link_to "Back to rooms", rooms_path, class: "ml-2 lnk_btn" %>
</div>

apps/app/views/rooms/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="text-4xl font-bold">Rooms</h1>
    <%= link_to 'New Room', new_room_path, class: "new_btn" if admin_signed_in? %>
  </div>

  <div id="rooms" class="min-w-full">
    <%= render @rooms %>
  </div>
</div>

apps/app/views/rooms/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New room</h1>

  <%= render "form", room: @room %>

  <%= link_to "Back to rooms", rooms_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

apps/app/views/rooms/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">

    <%= render @room %>

    <%= link_to "Edit this room", edit_room_path(@room), class: "mt-2 lnk_btn" %>
    <%= link_to "Back to rooms", rooms_path, class: "ml-2 lnk_btn" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this room", @room, method: :delete, class: "mt-2 lnk_btn" %>
    </div>
  </div>
</div>