apps/config/routes.rb
Rails.application.routes.draw do
  resources :calenders
  resources :rooms

  root "rooms#index"

  devise_for :admins, controllers: {
                        registrations: "admins/registrations",
                        sessions: "admins/sessions",
                      }

  devise_for :users, controllers: {
                       registrations: "users/registrations",
                       sessions: "users/sessions",
                     }
end

apps/app/models/calender.rb
class Calender < ApplicationRecord
end

apps/app/controllers/calenders_controller.rb
class CalendersController < ApplicationController
  before_action :set_calender, only: %i[ show edit update destroy ]

  # GET /calenders or /calenders.json
  def index
    @calenders = Calender.all
  end

  # GET /calenders/1 or /calenders/1.json
  def show
  end

  # GET /calenders/new
  def new
    @calender = Calender.new
  end

  # GET /calenders/1/edit
  def edit
  end

  # POST /calenders or /calenders.json
  def create
    @calender = Calender.new(calender_params)

    respond_to do |format|
      if @calender.save
        format.html { redirect_to calender_url(@calender), notice: "Calender was successfully created." }
        format.json { render :show, status: :created, location: @calender }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @calender.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calenders/1 or /calenders/1.json
  def update
    respond_to do |format|
      if @calender.update(calender_params)
        format.html { redirect_to calender_url(@calender), notice: "Calender was successfully updated." }
        format.json { render :show, status: :ok, location: @calender }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @calender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calenders/1 or /calenders/1.json
  def destroy
    @calender.destroy

    respond_to do |format|
      format.html { redirect_to calenders_url, notice: "Calender was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calender
      @calender = Calender.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def calender_params
      params.require(:calender).permit(:day, :begin_time, :close_time, :interval_s, :interval_e, :unit_minute, :no_use)
    end
end

apps/app/helpers/calenders_helper.rb
module CalendersHelper
end

apps/app/views/calenders/_calender.html.erb
<div id="<%= dom_id calender %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Day:</strong>
    <%= calender.day %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Begin time:</strong>
    <%= calender.begin_time %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Close time:</strong>
    <%= calender.close_time %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Interval s:</strong>
    <%= calender.interval_s %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Interval e:</strong>
    <%= calender.interval_e %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Unit minute:</strong>
    <%= calender.unit_minute %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">No use:</strong>
    <%= calender.no_use %>
  </p>

</div>

apps/app/views/calenders/_form.html.erb
<%= form_with(model: calender, class: "contents") do |form| %>
  <% if calender.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(calender.errors.count, "error") %> prohibited this calender from being saved:</h2>

      <ul>
        <% calender.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :day %>
    <%= form.date_field :day, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :begin_time %>
    <%= form.datetime_field :begin_time, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :close_time %>
    <%= form.datetime_field :close_time, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :interval_s %>
    <%= form.datetime_field :interval_s, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :interval_e %>
    <%= form.datetime_field :interval_e, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :unit_minute %>
    <%= form.number_field :unit_minute, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :no_use %>
    <%= form.check_box :no_use, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

apps/app/views/calenders/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing calender</h1>

  <%= render "form", calender: @calender %>

  <%= link_to "Show this calender", @calender, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to calenders", calenders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

apps/app/views/calenders/index.html.erb
<div class="w-full">

  <% content_for :title, "Calenders" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Calenders</h1>
    <%= link_to "New calender", new_calender_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="calenders" class="min-w-full">
    <% @calenders.each do |calender| %>
      <%= render calender %>
      <p>
        <%= link_to "Show this calender", calender, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

apps/app/views/calenders/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New calender</h1>

  <%= render "form", calender: @calender %>

  <%= link_to "Back to calenders", calenders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

apps/app/views/calenders/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">

    <%= render @calender %>

    <%= link_to "Edit this calender", edit_calender_path(@calender), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to calenders", calenders_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this calender", @calender, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>